### ISSUE TITLE
Stem package

### ISSUE THREAD

**Issue by bornakke** [medialab/ANTA#16]
I will suggest that the following instructions are added to the troubleshooting section of the readme file:

If you are getting errors from the system not being able to find to find anything starting with stem (e.g. the function stem_english) your php installation are missing the stem extension. If you have pecl working this can be solved by running the command:

'sudo pecl install stem'

This however failed at my system. You can then make a manual installation with the following steps:

1) Download the package (e.g. version 1.5.1) from http://pecl.php.net/package/stem.
2) Upload and unpack
3) Go to the folder containing the files of stem
4) Install by running 
phpize
./configure
make
make install

**Comment by danieleguido** [comment]
@bornakke 
Thanks again!
