### ISSUE TITLE
Installation: Step 9

### ISSUE THREAD

**Issue by ghost** [medialab/ANTA#19]
I get stuck in Step 9

"Add the following virtual host: Alias /anta_dev /path/to/anta/public

Options Indexes MultiViews FollowSymLinks AllowOverride All Order allow,deny Allow from all"

Can anyone elaborate on this step? How to do this? I am using Amazon AMI.

**Comment by bornakke** [comment]
Hi Amypu,

Normally you have to add it to a virtual host in your apache configuration. On a Ubuntu I would place it in the file /etc/apache2/sites-available/default and make it look something like:

<VirtualHost *:80>
        ServerName xx.dk
        ServerAlias www.xx.dk
        # Anta
        Alias /anta_dev "/path/to/anta/public_html/anta/public"
        <Directory /home/bornakke/public_html/anta/public/>
                Options Indexes MultiViews FollowSymLinks
                AllowOverride All
                Order allow,deny
                Allow from all
        </Directory>

**Comment by ghost** [comment]
Hi

Thanks very much for your prompt respose.

It looks like the file I need to modify is httpd.conf in /etc/httpd/conf
So, I have modified the file:

<VirtualHost *:80>

# ServerAdmin webmaster@dummy-host.example.com

# DocumentRoot /www/docs/dummy-host.example.com

# ServerName dummy-host.example.com

# ErrorLog logs/dummy-host.example.com-error_log

# CustomLog logs/dummy-host.example.com-access_log common

```
ServerName xx.xxx.xx.xx
ServerAlias xx.xxx.xx.xx
```

# Anta

```
Alias /anta_dev "/path/to/anta/public_html/anta/public"
<Directory />
Options Indexes MultiViews FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>
```

</VirtualHost>

I am able to open http://xx.xxx.xx.xx/anta/public/ and enter "dummy" as
username.
When I click "login", the browser opens
http://xx.xxx.xx.xx/anta_dev/index/login with the error message (Not Found).

The URL (http:/xx.xxx.xx.xx/anta_dev/) is also "not found".

Can you provide more hints?
Thanks

Amy

**Comment by bornakke** [comment]
Hi Amy,

1) Did you restart apache afterwards?
2) I thinnk that DocumentRoot will be needed and should be set to your public_html file?
3) Make sure that  Alias /anta_dev is set  to the correct path. Directory <Directory /> should be set to the same path so it end out looking something like this:
<Directory /path/to/anta/public_html/anta/public/>?

Hope some of it works out.

Best
Tobias

**Comment by ghost** [comment]
Hi Tobias

Thanks for the more information.

Can you clarify your point #3?

So far, I have something like this:

NameVirtualHost *:80

<VirtualHost *:80>
ServerName xx.xxx.xx.xx
ServerAlias xx.xxx.xx.xx
DocumentRoot /var/www/html
Alias /anta_dev /anta/public

<Directory /anta/public>
Options Indexes MultiViews FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>

http://www.xxx.xx.xx/anta_dev is Not found. The alias directory does not
seem to be working. Is this necessary?

I am able to open this page (http://www.xxx.xx.xx/anta/public).

Thanks

**Comment by bornakke** [comment]
Alias and Directory has to be the full path tot the public folder, e.g.:
/var/www/html/anta_dev /anta/public

And yes you need the alias to make it work with images and alike.

**Comment by ghost** [comment]
Great. xx.xxx.xx.xx/anta_dev works. (but, xx.xxx.xx.xx/anta_dev/install is
NOT Found)
Then, I type in "admin" as user and the browser opens
xx.xxx.xx.xx/anta_dev/index/login, which is NOT Found. I don't there is a
folder or a file called "login" in my server. Am I on the right track?
I appreciate your assistance.

**Comment by bornakke** [comment]
Hi Amy,

It sounds like you alias is working (read: you are on the right track) but the <directory> is not. But I'm unsure how to found the error.

Best
Tobias

**Comment by danieleguido** [comment]
Hi Amy,

your alias sholud be something like `Alias /anta_dev /var/www/html/anta/public`
and your directory directive something like `<Directory /var/www/html/anta/public>`
That is, Directory directive and Alias target must point to your system absolute paths.
The `/anta_dev` part of the alias is your server relative path and indicates the address to be used in a browser.

A hint, maybe: did you check _RewriteRule_ value inside your .htaccess file?
Every request made to xx.xxx.xx.xx/anta_dev/ has to be executed via the public index.php file - Zend framework works this way.

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
# RewriteRule ^.*$ index.php [NC,L]
RewriteRule ^.*$ /anta_dev/index.php [NC,L]
```

hope it can solve your problem! 
Otherwise can you write us the result of your access.log file?

**Comment by ghost** [comment]
I appreciate your assistance. Changing my directory directive has made the
pages work properly. Thanks bunch!

Now I am in the step #10. A couple questions regarding how to proceed from
here.
1. xx.xxx.xx.xx/anta_dev/install page works. It says
   "userAlreadyExistsFolder" and shows two input boxes: username and password.
   What username and password am I supposed to type before clicking Login
   button?

I typed in "admin" in username without password and pressed the login
button. This takes me to xx.xxx.xx.xx/anta_dev/index/login

The xx.xxx.xx.xx/anta_dev/index/login page says "password '' must be at
least 4 characters in length" so I typed in "hello". This results in an
error message "login credentials are not valid".
1. What needs to be done to fix this error?

If this is something to do with .htaccess file, then I will try to make the
changes you wrote to the file. By the way, there seems to be many .htaccess
files in different folders in my apache server so I am not sure which file
I need to change (I'm using Amazon Linux AMI and relatively new to Linux).
If my access.log file is helpful, I will write it to you as well.

Also, it looks like ANTA2 has been released. Is the installation
instruction available?

Thank you again!

**Comment by danieleguido** [comment]
Hi Amy,

the install action add a default "global" admin user. You will be able to login with 
user: dummy
p: admini

and then you _must_ change admin password by clicking on _your account_ on the right.
Then you can create as many account as is needed (_show users_, then _add user_). Each account handles a separate corpus.
And yes, there is a ANTA2 version - a simpler I hope; it is under development, but it lacks documentation. Feel free to open a github issue!

Thanks
Daniele

**Comment by bornakke** [comment]
@danieleguido Exciting news. How far is development? Is it being used for analysis or is it mostly testing yet?

**Comment by ghost** [comment]
Hi Daniele

Thanks for your assistance. Now I am able to log in! But, there seems to be
some other issues.

Once I log in, I see the following message "Notice: Undefined index:
index.index in
/var/www/html/anta/application/models/Ui/Boards/IdentityBoard.php on line
32 Notice: Undefined index: index.index in
/var/www/html/anta/application/models/Ui/Boards/IdentityBoard.php on line
32"

In modifying user dummny page,
"Notice: Undefined index: users.whois in
/var/www/html/anta/application/models/Ui/Boards/IdentityBoard.php on line
32"

In "uploading document" page, "
Notice: Trying to get property of non-object in
/var/www/html/anta/library/Ui/Boards/Documents.php on line 45 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Ui/Boards/Documents.php on line 50"

I uploaded four sample txt files, the result is "failed" with these errors:

Log of ajax-responses
xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31 Warning:
file_put_contents(/var/www/html/anta/application/../logs/test_encoding_dummy.log):
failed to open stream: Permission denied in
/var/www/html/anta/library/Anta/Logging.php on line 69 Cannot open file
(/var/www/html/anta/application/../logs/test_encoding_dummy.log)
xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31 Warning:
file_put_contents(/var/www/html/anta/application/../logs/test_encoding_dummy.log):
failed to open stream: Permission denied in
/var/www/html/anta/library/Anta/Logging.php on line 69 Cannot open file
(/var/www/html/anta/application/../logs/test_encoding_dummy.log)
xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31 Warning:
file_put_contents(/var/www/html/anta/application/../logs/test_encoding_dummy.log):
failed to open stream: Permission denied in
/var/www/html/anta/library/Anta/Logging.php on line 69 Cannot open file
(/var/www/html/anta/application/../logs/test_encoding_dummy.log)
xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31 Warning:
file_put_contents(/var/www/html/anta/application/../logs/test_encoding_dummy.log):
failed to open stream: Permission denied in
/var/www/html/anta/library/Anta/Logging.php on line 69 Cannot open file
(/var/www/html/anta/application/../logs/test_encoding_dummy.log)

In other pages, I see such messages as:

Notice: Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Undefined variable: type in
/var/www/html/anta/library/Ui/Forms/Elements/Option.php on line 28 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Ui/Boards/Documents.php on line 45 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Ui/Boards/Documents.php on line 50

Is this something to with the .htaccess file? Any further guidance?

Thanks again!

**Comment by bornakke** [comment]
Hi Amy,

Notice is not neccecary an error, but can also be some programming done a little wrong. You can change php to hide these from you. 

the error you are getting are most probably due to your logs folder not being writtable. Try to chmod it to 777.

**Comment by ghost** [comment]
Thanks again for your assistance. I am reporting what I have done so far.

---

This is what is in .htaccess file:
RewriteEngine On
 RewriteCond %{REQUEST_FILENAME} -s [OR]
 RewriteCond %{REQUEST_FILENAME} -l [OR]
 RewriteCond %{REQUEST_FILENAME} -d
 RewriteRule ^._$ - [NC,L]
 # RewriteRule ^._$ index.php [NC,L]
 RewriteRule ^.*$ /anta_dev/index.php [NC,L]

---

I have made my logs folder being writtable using chmod -R 777 .

---

Below is the result from my experiment of ANTA so far.

Step 1. Load documents. I loaded five txt files, but the loading failed
(see the error message below).

·         cv000_29416.txt3.9kBFailed
·         cv001_19502.txt1.3kBFailed
·         cv002_17424.txt2.8kBFailed
·         cv003_12683.txt2.9kBFailed
·         cv004_12641.txt4.3kBFailed

Log of ajax-responses

xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31
{"status":"ok","action":"upload","token":"ul809mjmd6nbcmtp8kdsudgo04","savedTags":{"categories":[],"tags":[]},"link":"\/anta_dev\/edit\/props\/user\/66q\/document\/x0j","mimeType":"text\/plain","result":"_2_cv001_19502.txt
(1357 bytes) added"}

xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31
{"status":"ok","action":"upload","token":"ul809mjmd6nbcmtp8kdsudgo04","savedTags":{"categories":[],"tags":[]},"link":"\/anta_dev\/edit\/props\/user\/66q\/document\/5pl","mimeType":"text\/plain","result":"_3_cv000_29416.txt
(4008 bytes) added"}

xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31
{"status":"ok","action":"upload","token":"ul809mjmd6nbcmtp8kdsudgo04","savedTags":{"categories":[],"tags":[]},"link":"\/anta_dev\/edit\/props\/user\/66q\/document\/vw7","mimeType":"text\/plain","result":"_2_cv002_17424.txt
(2825 bytes) added"}

xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31
{"status":"ok","action":"upload","token":"ul809mjmd6nbcmtp8kdsudgo04","savedTags":{"categories":[],"tags":[]},"link":"\/anta_dev\/edit\/props\/user\/66q\/document\/ki4","mimeType":"text\/plain","result":"_2_cv003_12683.txt
(2908 bytes) added"}

xhr - server response received
responseText = Notice: Undefined index: - in
/var/www/html/anta/library/Dnst/Crypto/SillyCipher.php on line 31
{"status":"ok","action":"upload","token":"ul809mjmd6nbcmtp8kdsudgo04","savedTags":{"categories":[],"tags":[]},"link":"\/anta_dev\/edit\/props\/user\/66q\/document\/jyz","mimeType":"text\/plain","result":"_2_cv004_12641.txt
(4381 bytes) added"}

Step 2. Tag Docs. See the error message below.

Trying to get property of non-object in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Undefined variable: identity in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Undefined variable: identity in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Undefined variable: identity in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Undefined variable: identity in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Trying to get property of non-object in
/var/www/html/anta/library/Anta/Ui/Item/Document.php on line 41 Notice:
Undefined index: REFERRER_URI in
/var/www/html/anta/library/Anta/Ui/Header/Documents.php on line 157

Step 3. Include entities
There is an empty graph

Step 4. Tag entities: Ups ... application error

Step 5 Export: Ups ... application error

---

Below is the result of sudo tail -10 /etc/httpd/logs/access_log

[ec2-user@ip-10-253-71-114 ~]$ sudo tail -10 /etc/httpd/logs/access_log                                                               xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:10 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:16 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:22 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:30 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:36 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:43 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:49 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:03:55 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:04:02 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" xx.xxx.xxx.xxx - - [05/Apr/2014:03:04:07 +0000] "GET /anta_dev/api/read-log/user/egd HTTP/1.1" 200 518 "http://xx.xxx.xx.xx/anta_dev/logs/read/user/66q" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36" 

---

Please let me know if I can write any other information. Thanks again!

**Comment by bornakke** [comment]
Could you tail the error.log file?

**Comment by ghost** [comment]
Thanks again!

[Sat Apr 05 15:15:07 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:12 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:18 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:24 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:30 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:36 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:42 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:48 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:15:54 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:00 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:06 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:12 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:19 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:24 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:30 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:36 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:42 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:48 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:16:54 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:00 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:06 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:12 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:18 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:24 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:30 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:36 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:42 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:48 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:17:55 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:00 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:06 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:12 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:18 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:24 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:30 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

tail: cannot open
'/var/www/html/anta/application/../logs/distillerlog_dummy' for reading: No
such file or directory

[Sat Apr 05 15:18:36 2014] [error] [client xx.xxx.xxx.xxx] PHP Notice:
 Undefined
variable: pidFile in
/var/www/html/anta/application/controllers/ApiController.php on line 182,
referer: http://xx.xxx.xxx.xxx/anta_dev/logs/read/user/66q

**Comment by bornakke** [comment]
Sorry I really don't have a clue what is going on :(

**Comment by bornakke** [comment]
because you have pressed 'analysis' (left middle) and started the backend right'?
