### ISSUE TITLE
Feature Requests for ANTA

### ISSUE THREAD

**Issue by bhargavvader** [medialab/ANTA#24]
Hello, I wanted to know if there any new feature ideas for this project in the pipeline. I have experience in using NLTK and Natural Language Processing and would love to contribute by implementing a new feature or working on old ones.

**Comment by bhargavvader** [comment]
Ping @danieleguido

**Comment by danieleguido** [comment]
Hi @bhargavvader,
There is no plan for the moment being :( from my side at least)

**Comment by bhargavvader** [comment]
Okay - do keep posted on the thread if anybody from the MediaLab team is going to be interested in this soon :)

**Comment by boogheta** [comment]
Hi @bhargavvader, unfortunately, no one anymore at médialab is working on ANTA, which can now be considered as a deprecated project on our side. We have hopes to work on a rebuild from scratch one day but there are very little chances anyone will do much on this one from now on, sorry :/
