### ISSUE TITLE
.Htaccess

### ISSUE THREAD

**Issue by bornakke** [medialab/ANTA#7]
Hey ANTA,

We are starting up a small danish mapping site for the most common tools where ANTA of cause is one of our main priorities.

I however have quite some difficulties with the .htaccess file. In the package there are two .htaccess files (one .htaccess and one htacccess) inside the public folder, but none of them seems to works.

Mostly i'm uncertain where the htaccess file should be located - Inside the public folder (where it is located now) or in the root folder? Secondly do you need more than one htaccess file that redirect the user to the public folder or does the guest simply start in ants_dev/public folder?

Hope somebody can give me a hint with this.

Best regards
Tobias

**Comment by boogheta** [comment]
Have you tried to uncomment line 7 in .htaccess and comment line 8 instead ?

**Comment by danieleguido** [comment]
It should be available under the /public folder.

Please check the zend framework v.1.2 [quickstart](http://framework.zend.com/manual/1.12/en/learning.quickstart.create-project.html#learning.quickstart.create-project.vhost) in order to create a proper apache virtualhost. The line #8 in our .htaccess file simply handle the redirection with the apache Alias directive: every request starting with `http://host.com/anta_dev/...` will be redirected to `http://host.com/anta_dev/index.php`.

In any case, here is the apache site we use:

```
Alias /anta_dev /path/to/anta/public

<Directory "path/to/anta/public">
   Options Indexes MultiViews FollowSymLinks
   AllowOverride All
   Order allow,deny
   Allow from all
</Directory>
```

**Comment by bornakke** [comment]
Thank you for your quick reply. It has gotten me quite a lot closer with style sheets and images now appearing :)

You can see the result here:
http://mapping.bornakke.dk/

I'm however still hitting some rocks, since the current code are not stringently dynamic. Making a quick search in the files shows that the server jiminy.medialab.sciences-po.fr and the folder /anta_dev/ has been hardcoded quite a lot of places :-/

I can point out the places for you if you need them, but it might be just as easy for you to simply run the search yourself. What do you prefere? 

Under all circumstances it seems like the necessary function to make it dynamic has already been build. So inserting Anta_Core::getBase() should do the job most of the places.

Finally when looking at the base, there might be a point in changing the default folder from anta_dev to something else, since servers running Cpanel (like mine), doesn't like the underscore when defining aliases.

Looking forward to your reply. Here in Denmark, we are all quite exciting in getting further involved with this valuable tool :)

Best regards
Tobias
