### ISSUE TITLE
documents table missing

### ISSUE THREAD

**Issue by bornakke** [medialab/ANTA#8]
Edit: Not an issue anyway. I had just missed the install part :)

**Comment by danieleguido** [comment]
Normally you should run the [install controller](https://github.com/medialab/ANTA/blob/master/application/controllers/InstallController.php)
which adds the admin user

**Comment by bornakke** [comment]
That was what I figured as well. Your use of a hardcoded database user with the name 'Anta' results however in some problems with out current server setup. 

So we will have to go back and check if we can get our hands on another server which allows us to create a user with the name anta and allow this user to create new databases.
